MCU = STM32F303
CTPC = yes
DEBUG_MATRIX_SCAN_RATE_ENABLE = yes
SERIAL_DRIVER = usart
WS2812_DRIVER = pwm
MOUSEKEY_ENABLE = yes
#RGBLIGHT_ENABLE = yes
VIA_ENABLE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes
AUDIO_ENABLE = no
GRAVE_ESC_ENABLE = no
EXTRAKEY_ENABLE = yes
COMMAND_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = yes
AUTO_SHIFT_ENABLE = no
SWAP_HANDS_ENABLE = no
CONSOLE_ENABLE = yes
COMBO_ENABLE = yes
BOOTMAGIC_ENABLE = no
TAP_DANCE_ENABLE = yes
POINTING_DEVICE_ENABLE = no
SPLIT_KEYBOARD = yes
RGBLIGHT_STARTUP_ANIMATION = yes

ifdef POINTING_DEVICE_ENABLE
	SRC += i2c_master.c
endif

ifeq ($strip $(WAFFLE)), yes)
	OPT_DEFS += -DWAFFLE
endif

